name: SPA Auto Claim and Stake

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  spa_auto_claim_and_stake:
    name: SPA Auto Claim and Stake

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"

      - run: npm install
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"

      - uses: mujo-code/puppeteer-headful@v2
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          SEED: ${{ secrets.SEED }}
          CI: "true"
        with:
          args: node index.js

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: recording
          path: recording.mp4

      - run: cat status.json
